### ISSUE TITLE
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (128, 128).

### ISSUE THREAD

**Issue by yuzhuovo** [FlorianFuerrutter/genQC#1]
Hello, when I run src/examples/0_hello_circuit.ipynb, this error occurs. May I ask how to change the size of attn_mask and how to solve this error?

**Comment by FlorianFuerrutter** [comment]
Hi, thanks for reporting this issue. 😀

The `open_clip` library changed the default transformer behavior to `batch_first=True` in a recent release. I fixed this in our code, please let me know if there are further issues.
